### ISSUE TITLE
is-fixedクラスを用意しておく

### ISSUE THREAD

**Issue by junichi-hnd** [team-lab/megane-tanaka-frontend#29]
#221　で使うであろう 
`.is-fixed` を用意

``` css
.is-fixed {
    position: fixed;
    top: ${y}px
    left: ${x}px
}
```

としておく
